### PR TITLE
Add Jetpack logo

### PR DESCRIPTION
**Pull request by johnHackworth**
This PR adds the Jetpack logo to social-logos. 

I'm using the same .svg we are using in https://github.com/Automattic/wp-calypso, and I have committed the result of adding it to `/svg` folder and running grunt. I'm not sure if I'm missing any step in thre process, thought.

### CODE REVIEW

**Comment by johnHackworth** [comment]
ping @jasmussen & @drw158

**Comment by jasmussen** [comment]
Fixed a few issues with the SVG. Vectors look good to me, but probably Dave should have a look as well, as he designed the logo — @drw158 I added the logo to the .ai file. 

We should also test the react component in Calypso, see that everything is up to snuff! Thanks for doing this, @johnHackworth !

**Comment by johnHackworth** [comment]
How should we do to test it in calypso? Replacing the local calypso social-logos module with a locally compiled one and visually test it?

**Comment by jasmussen** [comment]
> How should we do to test it in calypso? Replacing the local calypso social-logos module with a locally compiled one and visually test it?

I can't recall where in Calypso the social-logos component resides. But testing means running grunt on this PR, copying the resulting react/index.jsx file to where it's supposed to be in Calypso, and ensuring that Calypso successfully builds with no errors. Basically.

**Comment by johnHackworth** [comment]
Ok, I've just tested in my local wp-calypso environment, using social-logo instead of directly adding the svg in https://github.com/Automattic/wp-calypso/pull/3665 and everything seems to work ok. This is the result:

image

Probably it would be a good idea to someone with design eye to check it too for any kind of pixel blur or whatever, but it looks pretty good to me

**Comment by jasmussen** [comment]
Nice work, thanks for testing. Dave should definitely give the final thumbs up.

However, it's difficult to entirely avoid pixel blur when it comes to logos. Depends on whether we want to hint the social-logos Jetpack version. Up to Dave, I'd say.

**Comment by johnHackworth** [comment]
sounds good! :+1:

**Comment by drw158** [comment]
That issue is closed, so closing this for now until it comes up again.

**Pull request closed without merging**
