### PR TITLE
Fix the Bug Where the React Component Would Render No Icon

### PR DESCRIPTION
**Pull request by porada**
…at all despite properly passed properties.

The `switch` clause accepted a prefixed icon name, while all the `case`s matched their unprefixed versions, defaulting all icons to an empty SVG string.

### Testing instructions

* `git checkout fix/build`
* `npm install`
* `grunt`

### Notes

Once this has been merged, I’ll publish a new package version to `npm`.

### CODE REVIEW

**Comment by porada** [comment]
To be honest, I’m not sure what the best way to preview the component output is. I’m sourcing `social-logos` locally from within another project to make sure the icons render right.

**Comment by folletto** [comment]
Can you add a before-after screenshot? I know it's... very basic. :P 

Code seems good. There's one thing I can't really assess, which is: are there existing uses of this library that rely on that behaviour? If not, I think it's safe to merge.

Might be worth checking where the library is used and see if the way it's called won't break... just to play it safe ;)

**Comment by porada** [comment]
Before the patch, every single instance of `<SocialLogo icon="NAME" />` would result in a blank icon: `<svg height="24" width="24" /></svg>` (regardless of the icon name).

In the example of `<SocialLogo icon="facebook" />`:

```html
<!-- Before -->
<svg height="24" width="24" /></svg>

<!-- After -->
<svg class="social-logo social-logo-facebook" height="24" width="24" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><g><path d="M12 2C6.5 2 2 6.5 2 12c0 5 3.7 9.1 8.4 9.9v-7H7.9V12h2.5V9.8c0-2.5 1.5-3.9 3.8-3.9 1.1 0 2.2.2 2.2.2v2.5h-1.3c-1.2 0-1.6.8-1.6 1.6V12h2.8l-.4 2.9h-2.3v7C18.3 21.1 22 17 22 12c0-5.5-4.5-10-10-10z"></path></g></svg>
```

Given that this hasn’t been reported [since January 2018](https://github.com/Automattic/social-logos/blob/fix/build/CHANGELOG.md) makes me believe that the component hasn’t had much interest. I know Calypso doesn’t rely on it, but I’ll try to identify at least one other open source project that does.

**Comment by porada** [comment]
Updated the development dependencies (that wouldn’t affect the icons) to make the testing a little bit easier.

**Comment by folletto** [comment]
I understand the issue, I'm just wondering if there's any code that simply prefixes the content, so when this ships, they will break because they have already managed the prefix to make it work?

**Comment by porada** [comment]
To make it clearer, if you passed `social-logo-facebook` as the icon name, internally it would get prefixed once again to `social-logo-social-logo-facebook`.

With that, `case 'facebook'` never gets matched (doesn’t matter if the passed name is prefixed or not), resulting in a blank icon for _every_ possible version of the input.

It looks like the component has been unusable for all this time.

**Comment by folletto** [comment]
Ok, thanks for the clarification. Then I see no issue in shipping it. 👍

**Comment by porada** [comment]
@lsinger @folletto, thanks for chiming in! 🚢

**Comment by porada** [comment]
Published `social-logos@2.1.1`.

**Pull request merged**
