### PR TITLE
General Improvements

### PR DESCRIPTION
**Pull request by porada**
This pull requests introduces a bunch of maintenance-related things that will make future contributions a little easier:

* Include the built React assets in the repository, allowing the package to be referenced directly from GitHub.
    * Those assets are automatically generated before each commit, so they won’t be omitted.
    * This means that I can start using (or preview) the icon as soon as I submit a PR.
* Update build system dependencies responsible for minifying the icons and exporting the React assets.
    * I also regenerated and “locked” the PDF icons so that the files don’t appear wet the next somebody clones the repository from scratch (#93).
* Fix a bug in the demo page where the “Small Icons” toggle wouldn’t work.

**No visual changes have been introduced in this PR.**

### Testing instructions

* `git checkout feature/improvements`

#### Build system

* Make sure there aren’t any unstaged changes.
* `npm install`
* `grunt`
    * If it fails, try `git reset --hard` and `grunt` again.
* There shouldn’t be any unstaged changes at this point either. The repository should be clean.

#### Demo

* `cd docs`
* Run an HTTP server from the directory to make the SVG assets won’t get blocked:
    * `python -m SimpleHTTPServer 1234`
    * Enter `http://0.0.0.0:1234` in the browser.
* Ensure the “Small Icons” toggle works.

### CODE REVIEW

**Comment by folletto** [comment]
Nice :) 

> I also regenerated and “locked” the PDF icons so that the files don’t appear wet the next somebody clones the repository from scratch (#93).

This one was particularly tricky, thanks for taking care of it :) 

> SocialLogo

I think the name change is good too 👍

**Comment by porada** [comment]
> This one was particularly tricky, thanks for taking care of it :)

Let’s hope that works!

> I think the name change is good too 👍

The React component has had that name all along—it’s just the demo that suggested an incorrect one.

**Comment by davewhitley** [comment]
I followed the steps and everything seems to be working 👍

**Comment by porada** [comment]
@davewhitley, thanks for confirming. Merging soon.

**Comment by porada** [comment]
Published `social-logos@2.1.2`.

**Comment by noahtallen** [comment]
> I also regenerated and “locked” the PDF icons so that the files don’t appear wet the next somebody clones the repository from scratch (PDFKit is rebuilding files #93).

Unfortunately, this still appears to be happening to me :/

**Pull request merged**
