### PR TITLE
Add Behance logo

### LINKED ISSUE #17: Add Behance icon
A user has requested a Behance icon.

### PR DESCRIPTION
**Pull request by drw158**
Fixes #17 

I just added the svg for now.

screen shot 2016-02-16 at 3 03 19 pm

### CODE REVIEW

**Comment by jasmussen** [comment]
Looks good to me! :+1:

**Comment by drw158** [comment]
Ok, I updated from master and ran grunt. @jasmussen, can you check out the generated files one more time? Just wanted to make sure the task is running right.

**Comment by jasmussen** [comment]
> Ok, I updated from master and ran grunt. @jasmussen, can you check out the generated files one more time? Just wanted to make sure the task is running right.

Yep, no problem. But if it's not urgent I'd like to get #28 merged into master, then rebase this off of that first, as it changes how the icon font is built. It'll avoid some headaches.

**Comment by drw158** [comment]
Cool, no problem.

**Comment by jasmussen** [comment]
Rebased, grunted, it's looking good. I'm merging in.

**Pull request merged**
