### PR TITLE
Issue sweep

### LINKED ISSUE #19: Change Digg icon
As far as I can tell, Digg does not use the thumbs up icon anywhere anymore.

Because this repo is for logos, I suggest that we change the icon to one similar to their favicon:

screen shot 2016-02-04 at 12 17 10 pm

### LINKED ISSUE #20: Change share icon
I think we should change the share icon to the one we use in Gridicons, for consistency:

Current:
screen shot 2016-02-04 at 12 21 51 pm

Gridicons:
screen shot 2016-02-04 at 12 21 39 pm

### LINKED ISSUE #23: 2 WordPress logo layers in .ai file
They are the same as far as I can tell. We need to delete one.

### LINKED ISSUE #24: Medium icon missing from .ai file?
I don't see one.

### LINKED ISSUE #25: Spotify logo is altered from the "official" vector
Blue is the vector that I pulled from developer resources. https://developer.spotify.com/design/

Red is the current vector.
screen shot 2016-02-16 at 2 44 46 pm

### PR DESCRIPTION
**Pull request by drw158**
Fixing various issues:

Fixes #25
Fixes #24
Fixes #23
Fixes #20
Fixes #19

Updating logos if they were not the official vector asset:

- WhatsApp
- Medium
- Vimeo
- Spotify
- Stumbleupon
- Skype
- Instagram

Biggest change is new share icon:

screen shot 2016-02-18 at 4 50 04 pm

and removal of the digg icon.

### CODE REVIEW

**Comment by drw158** [comment]
@jasmussen I know it's quite a lot, but could you review this whenever you have a second? There aren't many big changes visual changes, but the code diff is quite large.

Might be best just to merge it without looking at the code :)

**Comment by drw158** [comment]
Exporting all new svgs with the script caused the most diffs

**Comment by jasmussen** [comment]
Lots of red and green here, nice issue sweep!

I'm a little bit concerned about that much red and green, though — exporting new SVGs from Illustrator to the svg directory shouldn't change the SVG source files at all, if we're doing it right. I wonder why the actual vector values are different.

I also noticed that some of the versions of the logos that have "alt" versions switched places. For example, the graphics for Twitter. `twitter` used to be the one with the roundrect, whereas this PR changes it to the one sans roundrect. I didn't doublecheck all of the alt versions, but there was a lot of red and green around `dropbox` vs.`dropbox-alt` also, same for `codepen` and `codepen-alt`. 

If the change from "twitter-alt" to "twitter" and vice versa was intentional, I'd be a little bit unnerved at doing those changes all in one fell swoop, I'd probably be more comfortable doing those changes in individual PRs rather than an issue-sweep like this, just so we know for absolutely sure the changes are intentional rather than just export mistakes.

On the other hand, if they are all intentional and you know what you're doing, perhaps better to get it in sooner rather than later, as Sharedaddy will need an updated icon font asap to account for the changes.

**Comment by jasmussen** [comment]
Tested the react component in Calypso, and it compiles and seems to work just fine. 

My previous concern still stands, though — the main concern is that if a designer purposefully chose to use "twitter-alt" for a particular button, and the icon is suddenly swapped out for what used to be "twitter", things might look broken. 

screen shot 2016-02-19 at 10 32 49

**Comment by drw158** [comment]
Thanks for the review Joen, it was not my intention to switch the alt logo names. I'll check and see.

**Comment by drw158** [comment]
Nice catch Joen. Originally, when the repo was created, `twitter` was the non-rect version, and `twitter-alt` was the rect version. This was switched around the time we enabled the Calypso react component I believe. I have a strong suspicion that the svg files were renamed, but the .ai file was not updated. So, when I ran the export script, it was using the original layer file names.

I'll rename the layers so that it will ex.port right.

**Comment by jasmussen** [comment]
:+1: 

If you can, please have a look at the dropbox and some of the other very red/green one as well!

**Comment by drw158** [comment]
Ok, I got the ai file layer names straight and ran grunt. Unfortunately, a  lot of the changes are updating the AI version in the comments of the svg file.

One thing I noticed is that if I add a new icon, run grunt, and the decide to remove the icon later, the script doesn't remove some remnants of the icon in the generated files, like in codepoints.json.

**Comment by jasmussen** [comment]
> One thing I noticed is that if I add a new icon, run grunt, and the decide to remove the icon later, the script doesn't remove some remnants of the icon in the generated files, like in codepoints.json.

Hmm. This could be semi-intentional — let's say we add "example" icon to the icon font, and it gets a codepoint. Then "example" gets retired, and we remove it again. When the codepoint stays in the file, preventing other icons from adopting that codepoint (which could, in edgecases, cause CSS complications down the road).

But I'll dig a little into this -- depending on the behavior we should probably add some notes in the readme file.

**Comment by drw158** [comment]
moved to #31

**Pull request closed without merging**
