### PR TITLE
Add Mastodon Icon

### PR DESCRIPTION
**Pull request by timnolte**
Fixes issue #67 also to possible prepare the icon library for use by [JetPack Publicize Mastodon support](https://github.com/Automattic/jetpack/issues/7790) and potentially [JetPack Sharing Mastodon support](https://github.com/Automattic/jetpack/issues/10338).

### CODE REVIEW

**Comment by vskjefst** [comment]
Any chance of getting the merge conflicts resolved, and this PR merged to master? Would love to have the Mastodon icon in there.

**Comment by timnolte** [comment]
@vskjefst I can take a look at what the merge conflict is. Seems like merging is up to repository maintainers.

**Comment by vskjefst** [comment]
@ockham what's the chance of getting this PR merged when @timnolte has fixed the merge conflict?

**Comment by colincwilliams** [comment]
Bumping this PR given the recent meteoric rise in popularity of Mastodon. Understand if there's reasons it can't be a priority, but I figure it should be re-evaluated if it hasn't been already since things have changed.

(Yes, I want to use the icon on my site through this repo so I'm personally biased. But surely I'm not the only one. :))

**Comment by jeherve** [comment]
@timnolte Thanks a lot for the PR! It was a bit outdated (our fault, sorry, it's taken us quite some time to get to your request!), so I ended up creating #115 to replace this PR. I'll see about getting us moving in that other PR.

**Pull request closed without merging**
