### PR TITLE
Added copy post url button.

### PR DESCRIPTION
**Pull request by spsiddarthan**
Fixes https://github.com/Automattic/social-logos/issues/111

How did I make this change?

- I just added the SVG file to the sources directory and ran grunt, let me know if I should do something else as well. 

After the PR is merged, we can publish to npm as well. I picked the icon SVG from [~~this comment~~](https://github.com/Automattic/social-logos/issues/111#issuecomment-1005705261) [gridicons](https://github.com/Automattic/gridicons/blob/trunk/sources/svg/gridicons-link.svg).

### CODE REVIEW

**Review by davewhitley — CHANGES_REQUESTED** [review]
Can you use the icon from [Gridicons](https://github.com/Automattic/gridicons) instead? The one you used will need to be part of a bigger update (we'd need to update print, mail, etc. all in one go).

Also let's keep the name "link" instead of "copy link" to stay consistent with print and mail icons.

Thanks!

**Comment by spsiddarthan** [comment]
Hi @davewhitley, thank you for your comments. 

I amended the PR, let me know if there is anything else we would need to do. 

>The one you used will need to be part of a bigger update (we'd need to update print, mail, etc. all in one go).

Should I perhaps open a new issue for this bigger update?

**Review by davewhitley — APPROVED** [review]
Looks good. We'll need to update npm next

**Comment by spsiddarthan** [comment]
@davewhitley, Thanks for your review.  :) 

It's a tad late where I am, so I am going to continue with this on Monday but wanted to ask the following, so I can work on them in the next week. 

Should I update the npm after merging this PR to the trunk branch?  

I understand these are the steps

```
Bump package version in package.json to the next desired version and add an alpha postfix 1.1.0-alpha.1
While testing changes publish using the next tag npm publish --tag next
If changes look good remove postfix in version 1.1.0
Publish using the latest tag npm publish --tag latest
```
Could you please tell me what `add an alpha postfix 1.1.0-alpha.1` means? I am doing this for the first time and just wanted to be sure I got everything right.

**Comment by spsiddarthan** [comment]
Hi @davewhitley, 

I have bumped the version in the package.json file to `2.5.0-alpha.1`.

Correct me, if there are the things to do next:

- Merge the PR to the trunk branch
- Publish the `2.5.0-alpha.1` version to npm
- Test the published npm `2.5.0-alpha.1` version in another JS package and make sure everything is working
- Update the package.json to 2.5.0 (remove the alpha suffix) and publish to npm again

**Comment by davewhitley** [comment]
Yep I think that is right

**Comment by spsiddarthan** [comment]
Will leave a comment here as soon as I publish to npm.

**Comment by spsiddarthan** [comment]
Published 2.5.0 to npm .

**Pull request merged**
