### PR TITLE
Add WooCommerce icon

### PR DESCRIPTION
**Pull request by jameskoster**
icon

Based on the woocommerce.com Favicon, using the bubble from the [WC logo](https://woocommerce.com/style-guide/#sg-logo).

### CODE REVIEW

**Comment by jameskoster** [comment]
Should have noted - the corner radii are from the original logo - scaled down. They're pretty close to lining up perfectly with our grid. Curious if there's any benefit to making this small tweak?

**Comment by folletto** [comment]
> Curious if there's any benefit to making this small tweak?

I'd check the pixel preview. If it makes it sharper, I'd tweak. :)

**Comment by jameskoster** [comment]
That's pixel preview, one with aligned radii, one with scaled-down radii from the original logo.

Not really any difference to my eye.

**Comment by folletto** [comment]
Is that at the default 24px? Can we maybe tweak it slightly so the edges are all sharp at that size? :)

**Comment by drw158** [comment]
The edges on the left icon are much fuzzier.

**Comment by jameskoster** [comment]
Strange, looks like that might be an up-scaling issue with macOS and screenshots. Here's the exported version;



The edges are all from a rectangle that was drawn with snap-to-pixel on, so I'm not sure why it's looking fuzzy in the pixel preview...

**Comment by folletto** [comment]
That looks good.
There seem to be a slight blur still on the bottom edge, do you think it's worth fixing for sharpness?

**Comment by jameskoster** [comment]
That's fixable but means breaking the grid;

**Comment by folletto** [comment]
Hah! Looking good :)

**Comment by jameskoster** [comment]
Cheers. If you wouldn't mind approving @folletto I'll go ahead and merge this in.

**Pull request merged**
