### PR TITLE
Issue sweep

### LINKED ISSUE #19: Change Digg icon
As far as I can tell, Digg does not use the thumbs up icon anywhere anymore.

Because this repo is for logos, I suggest that we change the icon to one similar to their favicon:

screen shot 2016-02-04 at 12 17 10 pm

### LINKED ISSUE #20: Change share icon
I think we should change the share icon to the one we use in Gridicons, for consistency:

Current:
screen shot 2016-02-04 at 12 21 51 pm

Gridicons:
screen shot 2016-02-04 at 12 21 39 pm

### LINKED ISSUE #23: 2 WordPress logo layers in .ai file
They are the same as far as I can tell. We need to delete one.

### LINKED ISSUE #24: Medium icon missing from .ai file?
I don't see one.

### LINKED ISSUE #25: Spotify logo is altered from the "official" vector
Blue is the vector that I pulled from developer resources. https://developer.spotify.com/design/

Red is the current vector.
screen shot 2016-02-16 at 2 44 46 pm

### PR DESCRIPTION
**Pull request by drw158**
#30 was getting a bit too complex, so I started fresh

Fixing various issues:

Fixes #25
Fixes #24
Fixes #23
Fixes #20
Fixes #19

Updating logos if they were not the official vector asset:

- WhatsApp
- Medium
- Vimeo
- Spotify
- Stumbleupon
- Skype
- Instagram

Biggest change is new share icon:

screen shot 2016-02-18 at 4 50 04 pm

and removal of the digg icon.

cc @jasmussen

### CODE REVIEW

**Comment by jasmussen** [comment]
Thanks again for doing this. I can review it next week, a bit busy today.

**Comment by jasmussen** [comment]
Added the icon font to the grunt mix. Does it not bake when you grunt?

In any case, too a look at the diffs, and it's all looking much better. At some point in the future we should probably add better and more specific export instructions from Illustrator, as I noticed that the cases with a lot of red and green in the SVG source diffs, were different due to more decimal places in your exports. Which is fine, but might as well specify exact decimal places when people export, so as to minimize these diffs.

Great work, ship ship ship! :+1:

**Comment by drw158** [comment]
Thanks for the review, not sure about the decimal place. I use the export script, but maybe there's a difference in the version I'm using or maybe a settings somewhere. I agree about the instructions. Thanks!

**Comment by jasmussen** [comment]
> not sure about the decimal place

Some apps round up decimal places more than other. I think in Illustrator you can choose how many decimal places. The fewer, the more lossy, the more, the less compressed. But nothing to hold up this PR.

**Pull request merged**
