### PR TITLE
Update svg attrs to camel case to avoid react dom warning

### PR DESCRIPTION
**Pull request by gwwar**
With React 15, SVG is now supported but attributes must be 🐫  cased. This will throw a warning otherwise. https://facebook.github.io/react/docs/dom-elements.html#all-supported-svg-attributes

We accidentally fixed this upstream in Calypso first:  https://github.com/Automattic/wp-calypso/pull/8590

This PR updates the grunt task to transform svg attributes from kabob-case to camelCase. 

## Testing Instructions
- `npm install`
- Install system dependent font deps https://github.com/sapegin/grunt-webfont
- `$(npm bin)/grunt --verbose`
- generated output should be the same

cc @drw158 @folletto @obenland

### CODE REVIEW

**Comment by folletto** [comment]
Just for clarity: this change happens exclusively in JSX as it would break "plain" SVGs elsewhere, is that correct?

If that's the case, shouldn't the change above happen in the generator, as that's a [generated file](https://github.com/Automattic/social-logos/blob/75007c2c9a6ab93a09cd44ec93931d3c3001ab22/react/social-logo/index.jsx#L3)?

Ref: https://github.com/Automattic/social-logos/blob/master/Gruntfile.js#L180

**Comment by gwwar** [comment]
> If that's the case, shouldn't the change above happen in the generator

Whoops missed that again. I feel like we should put generated files into a build folder. I'll fix

**Comment by gwwar** [comment]
@folletto this is ready for another look when you have time

**Comment by folletto** [comment]
Seems good to me.

I had an odd error triggered when `fontforge` isn't installed which makes all the sizing `<rect x="0" fill="none" width="24" height="24"/>` disappear, but seems unrelated to this. I'm mentioning just to have a reference in the future if it happens again.

This PR looks good. I just added a comment on the code.

**Comment by folletto** [comment]
Aside: should we get this change to Gridicons as well?

**Comment by gwwar** [comment]
> Aside: should we get this change to Gridicons as well?

Seems reasonable if it shares the same build process.

Thanks for the review @folletto, I'll be merging this in then

**Pull request merged**
