### PR TITLE
Build: refactor build system to align to Gridicons'

### PR DESCRIPTION
**Pull request by folletto**
This refactoring of the whole build system makes the repository aligned with the same build system of Gridicons.

Benefits:

* SVG are masters
* More modular, we can share tasks across
* Cleanly separated sources folder
* More automation
* Less dependencies (font-forge not required)

---

To test: 

* Try to run the build from scratch: `npm install` + `npm run build`.
* Check all the built files: React component, Demo, SVGs, PDFs, font file.
* Make sure there's no regression from master.

---

These are the corresponding Gridicons/Dashicons main changes to the build system for reference:

* https://github.com/Automattic/gridicons/pull/241
* https://github.com/Automattic/gridicons/pull/230
* https://github.com/Automattic/gridicons/pull/217
* https://github.com/WordPress/dashicons/pull/215

### CODE REVIEW

**Comment by jasmussen** [comment]
Damn this is clean and nice. All looks good to me, and impressive how you managed to get the PDF system into it. 👍 👍 delicious!

**Comment by folletto** [comment]
Ok given this is a bit a low traffic repository and the icons seem all working, I'm going ahead to merge it — it would also make easier to track any follow-up change.

**Comment by gwwar** [comment]
Thanks for taking this on @folletto one thing to note is that we should probably add an engines section to specify the minimum node version in package.json if we want to commit a package-lock file.

[npm 5 wasn't paired with Node until the v8 LTS line](
https://nodejs.org/en/download/releases/), so folks who try to use this library will run into trouble if their project isn't at that version yet.

**Comment by folletto** [comment]
I thought the only addition was the `package-lock.json` file... which is relevant only for local build and ignored by previous versions? Maybe is it a wrong assumption?

We can add an engines section if you think it works better. I'm just not sure how to validate what's the minimum version we requite, but I can have a look.

**Pull request merged**
