### PR TITLE
Updates Medium Logo/Icon

### LINKED ISSUE #69: Update icon: Medium
We need to update our Medium icon to match their latest [branding](https://medium.design/logos-and-brand-guidelines-f1a01a733592). We use this icon in the importers section https://wordpress.com/settings/import/[site].wordpress.com.

image

image

I have an SVG for this icon from Medium's brand guidelines page (attached), but unfortunately I don't have the SVG skills to tweak it for inclusion in this package.

[Monogram.svg.zip](https://github.com/Automattic/wp-calypso/files/2473354/Monogram.svg.zip)

### PR DESCRIPTION
**Pull request by timnolte**
Fixes #69

* Updates Medium logo with new Monogram branding.
* Updates build with new Medium icon.

### CODE REVIEW

**Comment by andfinally** [comment]
Firstly @timnolte, thanks very much for looking at this and I'm really sorry that it's taken so long for anybody to review your PR. We still need this change! I'm not very sure of the reviewing process for this kind of Node package, but I've had a go at building your branch myself. I can see one or two issues.

Firstly, I didn't anticipate this, but most square logos with a black background in this set have rounded corners. The sharp-cornered icon Medium provide looks out of place among them:

image

Second, the PDF version ends up not centered within the canvas:

image

We get a similar result with the `svg-min` version, which also doesn't fill the available area:

image

And the `svg-min-react` version doesn't seem to render properly:

image

I'm sure all these positioning/sizing issues are because of some alignment or scaling setting in the SVG Medium provided.

**Comment by dezzie** [comment]
Hello there, I took a look at what might be going on here and it's a couple of things. You'll find the fixed/accurate assets attached to this comment.

The logo images are pulled from each platform's own branding guidelines, not a black and white set. 

When I inspected one of the other images, I saw that we are using a regular square image for the logo, and then setting it inside a square background of the same color. The background is the container that has the rounded corners on it. That's probably so that we don't make redundant assets and can preserve the original one to use elsewhere.

I went ahead and re-created the new Medium logo to solve any rendering issues, and because we do need to shave a bit off the sides to make the "M" look proportionately consistent with the other importer logo images. If it is easier to update the logo using a .png instead of an .svg I attached that here too.

The bg color of the updated Medium logomark should be #12100E:
[Updated Medium Logomark.zip](https://github.com/Automattic/social-logos/files/3107968/Updated.Medium.Logomark.zip)

**Comment by andfinally** [comment]
@timnolte The README on this repo isn't very helpful about how to add or modify logos. I'm not able to update the package with the new SVG. I've tried copying the new SVG into `sources/svg` and then running `npm run build`, but the build fails at `social-logos@2.1.0 build script`. Would you like to have a go using the new SVG Dezzie's added?

**Comment by timnolte** [comment]
@andfinally Yeah, sorry, life has been crazy recently and haven't had a lot of free time to get to this. I'll try to take a look tonight.

**Comment by timnolte** [comment]
@andfinally from everything I see the logo file uploaded by @dezzie doesn't appear to be an SVG designed to work with the build process, to start it's not a 24x24 pixel SVG. I'm going to need to work on changing the SVG supplied to get it sized properly. I thought I had originally created the SVG using the icon-template.ai file in the sources directory. @dezzie if you didn't you should use the icon-template.ai file as your starting point for the work. I ran out of time to make the required changes as my build was failing and was concerned it was due to npm updates related to other development efforts only to finally figure out it was because of the incorrect new SVG file. Thanks!

**Comment by andfinally** [comment]
No rush @timnolte, thanks a lot for having a look and well done on narrowing it down. I think you're right, because I've tried the build again with a version of the original SVG with the dimensions removed from the `svg` element - the build completes OK this time, but the Medium logos come out as black squares. 

I obviously didn't give @dezzie enough info, sorry Dezzie! I'm going to see if I can get any tips from a previous contributor on what the best procedure for updating logos is, and hopefuly add more info to the README so other people don't run into this problem.

**Comment by andfinally** [comment]
Dave Whitley tells me the procedure for updating this package should be very similar to the one for [Gridicons](https://github.com/Automattic/gridicons) - the key seems to be that the SVG should be based on the [icon-template.ai](https://github.com/Automattic/social-logos/blob/master/sources/icon-template.ai). Dave's suggested we try this [SVG](https://github.com/Automattic/social-logos/files/3117373/medium.svg.zip). Unfortunately the build is still failing for me with the message

`Warning: build/index.jsx: Unexpected token, expected } (109:190)`

Maybe you can give it a try whenever you get the time Tim, in case this is due to some misconfiguration on my end.

**Comment by dezzie** [comment]
No worries @timnolte, I appreciate the explanation for the next time I will probably run into this. If @drw158 suggested another SVG I trust his judgment.

**Comment by davewhitley** [comment]
I am taking a look at this again. Even though Medium just rebranded again, I don't think the [new icon](https://medium.design/logos-and-brand-guidelines-f1a01a733592) is very distinctive (the 3 circle shapes). I suggest we stick with the wordmark "M" version for now, unless someone feel strongly about using the new icon.

Here is the new icon, redrawn, and optimizes to fit within our guidelines:

Screen Shot 2021-01-26 at 1 49 45 PM

SVG: https://cloudup.com/clIbclt3Z-M

Square corners have been retained since that was a purposeful shape from the Medium logo (similar to Eventbrite, etc.)

**Pull request closed without merging**
